name: l3d
channels:
  - pyg
  - pytorch
  - pytorch3d
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
#  - cudatoolkit=11.0
#  - python=3.9
  - pip
  - pytorch
  - pytorch3d
  - torchvision
  - fvcore
  - iopath
  - nvidiacub
  - pip:
    - hydra-core
    - Pillow
    - plotly
    - requests
    - imageio
    - matplotlib
    - numpy
    - PyMCubes
    - tqdm
    - visdom
    - nuscenes-devkit
    - tensorboardX
    - efficientnet_pytorch==0.7.0
